//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praesidium.Data_Models.Admin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdminEntities : DbContext
    {
        public AdminEntities()
            : base("name=AdminEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ShSyNavigationItem> ShSyNavigationItems { get; set; }
        public virtual DbSet<ShSySection> ShSySections { get; set; }
        public virtual DbSet<ShUser> ShUsers { get; set; }
        public virtual DbSet<ShUserType> ShUserTypes { get; set; }
        public virtual DbSet<ShFile> ShFiles { get; set; }
        public virtual DbSet<ShFileKeyword> ShFileKeywords { get; set; }
    }
}
