//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praesidium.Data_Models.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShSySecurityItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShSySecurityItem()
        {
            this.ShRlShUserTypeToShSySecurityItems = new HashSet<ShRlShUserTypeToShSySecurityItem>();
        }
    
        public int RecId { get; set; }
        public int FkShSyNavigationItem { get; set; }
        public int Access { get; set; }
        public string SecurityItem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShRlShUserTypeToShSySecurityItem> ShRlShUserTypeToShSySecurityItems { get; set; }
        public virtual ShSyNavigationItem ShSyNavigationItem { get; set; }
    }
}
